#!/usr/bin/env node
/**
 * Build REPORT.md from k6 *.summary.json files in a baseline folder.
 * Usage: node plan/load-tests/generate-report.mjs plan/load-tests/baselines/results/localhost/2026-06-16
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, basename } from 'path';

const outDir = process.argv[2];
if (!outDir) {
  console.error('Usage: node generate-report.mjs <baseline-folder>');
  process.exit(1);
}

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function metricValue(summary, name, key = 'p(95)') {
  const m = summary?.metrics?.[name]?.values ?? summary?.metrics?.[name];
  if (!m) return null;
  if (typeof m === 'number') return m;
  return m[key] ?? m.avg ?? m.value ?? null;
}

function formatMs(v) {
  if (v == null) return '—';
  return `${Math.round(v)} ms`;
}

function formatRate(v) {
  if (v == null) return '—';
  return `${(v * 100).toFixed(2)}%`;
}

function formatRps(v) {
  if (v == null) return '—';
  return v.toFixed(2);
}

const manifestPath = join(outDir, 'manifest.json');
const manifest = existsSync(manifestPath) ? readJson(manifestPath) : {};

const summaries = readdirSync(outDir)
  .filter((f) => f.endsWith('.summary.json'))
  .sort()
  .map((f) => {
    const script = f.replace('.summary.json', '');
    const data = readJson(join(outDir, f));
    return {
      script,
      p95: metricValue(data, 'http_req_duration'),
      avg: metricValue(data, 'http_req_duration', 'avg'),
      failRate: metricValue(data, 'http_req_failed', 'rate'),
      rps: metricValue(data, 'http_reqs', 'rate'),
      checks: metricValue(data, 'checks', 'passes'),
    };
  });

const lines = [
  `# k6 baseline — ${manifest.runId ?? basename(outDir)}`,
  '',
  '| Field | Value |',
  '|-------|-------|',
  `| Recorded | ${manifest.recordedAt ?? '—'} |`,
  `| Target | ${manifest.target ?? '—'} |`,
  `| BASE_URL | ${manifest.baseUrl ?? '—'} |`,
  `| Git | ${manifest.gitBranch ?? '—'} @ ${manifest.gitSha ?? '—'} |`,
  `| k6 | ${manifest.k6Version ?? '—'} |`,
  '',
  '## Results',
  '',
  '| Script | p95 | avg | error rate | req/s |',
  '|--------|-----|-----|------------|-------|',
  ...summaries.map(
    (s) =>
      `| ${s.script} | ${formatMs(s.p95)} | ${formatMs(s.avg)} | ${formatRate(s.failRate)} | ${formatRps(s.rps)} |`
  ),
  '',
  '_Generated by `plan/load-tests/generate-report.mjs`_',
  '',
];

const reportPath = join(outDir, 'REPORT.md');
writeFileSync(reportPath, lines.join('\n'));
console.log(`Wrote ${reportPath}`);
